[build]
  publish = "."
  command = ""
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Netlify Functions plugin for automatic dependency installation
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Form handling - redirect Netlify's default success page to our custom page
[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200

# Contact form handling - functions are automatically available at /.netlify/functions/

# Form configuration
[[forms]]
  name = "contact"
  [forms.fields]
    name = { required = true }
    email = { required = true }
    phone = { required = true }
    message = { required = true }
    consent = { required = true }
  
  # Webhook configuration for form submissions
  [forms.webhook]
    url = "/.netlify/functions/form-webhook"
    event = "form_submission"

# Admin panel
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/"
  to = "/admin/index.html"
  status = 200

# Admin panel headers
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.google.com https://www.gstatic.com https://maps.googleapis.com https://maps.gstatic.com https://identity.netlify.com https://unpkg.com; style-src 'self' 'unsafe-inline'; connect-src 'self' https://maps.googleapis.com https://maps.gstatic.com https://identity.netlify.com; frame-src https://www.google.com https://identity.netlify.com; form-action 'self';"

[[headers]]
  for = "/admin/index.html"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.google.com https://www.gstatic.com https://maps.googleapis.com https://maps.gstatic.com https://identity.netlify.com https://unpkg.com; style-src 'self' 'unsafe-inline'; connect-src 'self' https://maps.googleapis.com https://maps.gstatic.com https://identity.netlify.com; frame-src https://www.google.com https://identity.netlify.com; form-action 'self';"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.google.com https://www.gstatic.com https://maps.googleapis.com https://maps.gstatic.com https://identity.netlify.com https://unpkg.com; style-src 'self' 'unsafe-inline'; connect-src 'self' https://maps.googleapis.com https://maps.gstatic.com https://identity.netlify.com; frame-src https://www.google.com https://identity.netlify.com; form-action 'self';"

# Cache static assets
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Service Worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Type = "application/javascript"

# Sitemap
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    Cache-Control = "public, max-age=3600"

# Robots.txt
[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"
    Cache-Control = "public, max-age=3600"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com https://identity.netlify.com https://www.google.com https://www.gstatic.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://api.netlify.com; frame-src https://www.google.com;"

# Form handling with Netlify reCAPTCHA
[[headers]]
  for = "/"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com https://identity.netlify.com https://www.google.com https://www.gstatic.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://api.netlify.com; frame-src https://www.google.com;"

# Netlify Forms configuration
[context.production.environment]
  NETLIFY_FORMS_RECAPTCHA = "true"
  GITHUB_TOKEN = ""
  GITHUB_REPO = ""

[context.deploy-preview.environment]
  NETLIFY_FORMS_RECAPTCHA = "true"
  GITHUB_TOKEN = ""
  GITHUB_REPO = ""

[context.branch-deploy.environment]
  NETLIFY_FORMS_RECAPTCHA = "true"
  GITHUB_TOKEN = ""
  GITHUB_REPO = ""
