backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "site_settings"
    label: "Ustawienia strony"
    folder: "data/site_settings"
    create: false
    slug: "site-settings"
    format: "json"
    fields:
      - {label: "Tytuł strony", name: "title", widget: "string"}
      - {label: "Opis strony", name: "description", widget: "text"}
      - {label: "Logo strony", name: "logo", widget: "image", required: false}
      - {label: "Favicon SVG", name: "favicon_svg", widget: "image", required: false}
      - {label: "Favicon 16x16", name: "favicon_16", widget: "image", required: false}
      - {label: "Favicon 32x32", name: "favicon_32", widget: "image", required: false}
      - {label: "Apple Touch Icon (180x180)", name: "favicon_180", widget: "image", required: false}
      - {label: "Android Chrome 192x192", name: "favicon_192", widget: "image", required: false}
      - {label: "Android Chrome 512x512", name: "favicon_512", widget: "image", required: false}
      - {label: "Telefon", name: "phone", widget: "string"}
      - {label: "E-mail", name: "email", widget: "string"}
      - {label: "Adres", name: "address", widget: "text"}
      - {label: "Prospekt informacyjny", name: "prospekt_file", widget: "string", required: false, hint: "Ścieżka do pliku prospektu (PDF, DOC, DOCX) - np. /images/uploads/prospekt-harmonia-rzaska.pdf", default: "/images/uploads/prospekt-harmonia-rzaska.pdf"}

  - name: "units"
    label: "Lokale"
    folder: "data/units"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}"
    format: "json"
    sortable_fields: ["id", "nr_budynku", "nr_lokalu", "cena", "status"]
    default_sort: "id"
    default_sort_direction: "asc"
    list:
      fields:
        - {label: "Lokal", name: "nr_lokalu", widget: "string"}
        - {label: "Budynek", name: "nr_budynku", widget: "string"}
        - {label: "Piętro", name: "pietro", widget: "number"}
        - {label: "Powierzchnia (m²)", name: "powierzchnia", widget: "number"}
        - {label: "Cena (zł)", name: "cena", widget: "number"}
        - {label: "Cena za m²", name: "cena_m2", widget: "number"}
        - {label: "Status", name: "status", widget: "select", options: ["WOLNE", "SPRZEDANE", "REZERWACJA"]}
    summary: "Lokal {{nr_lokalu}}\nBudynek {{nr_budynku}}\n{{powierzchnia}}m²\n{{cena}}zł\n{{cena_m2}}zł/m²\nStatus: {{status}}"
    fields:
      - {label: "ID", name: "id", widget: "number"}
      - {label: "Numer budynku", name: "nr_budynku", widget: "string"}
      - {label: "Numer lokalu", name: "nr_lokalu", widget: "string"}
      - {label: "Piętro", name: "pietro", widget: "number"}
      - {label: "Powierzchnia (m²)", name: "powierzchnia", widget: "number"}
      - {label: "Dodatki", name: "dodatki", widget: "text", required: false}
      - {label: "Cena (zł)", name: "cena", widget: "number"}
      - {label: "Cena za m² (zł)", name: "cena_m2", widget: "number", required: false, hint: "Obliczana automatycznie na podstawie ceny i powierzchni"}
      - {label: "Status", name: "status", widget: "select", options: ["WOLNE", "SPRZEDANE", "REZERWACJA"]}
      - {label: "URL planu", name: "plan_url", widget: "string", required: false}
      - {label: "Opis", name: "opis", widget: "text", required: false}

  - name: "contact_messages"
    label: "Wiadomości kontaktowe"
    folder: "data/contact_messages"
    create: false
    slug: "{{timestamp}}-{{name}}"
    format: "json"
    sortable_fields: ["timestamp", "name", "status"]
    default_sort: "timestamp"
    default_sort_direction: "desc"
    list:
      fields:
        - {label: "Data", name: "timestamp", widget: "datetime"}
        - {label: "Imię i nazwisko", name: "name", widget: "string"}
        - {label: "E-mail", name: "email", widget: "string"}
        - {label: "Telefon", name: "phone", widget: "string"}
        - {label: "Temat", name: "subject", widget: "string"}
        - {label: "Status", name: "status", widget: "select", options: ["new", "read", "replied", "archived"]}
        - {label: "Akcje", name: "actions", widget: "string", default: "📋 Kliknij aby zobaczyć szczegóły"}
    summary: "{{name}}\n{{email}}\n{{phone}}\n{{subject}}\n{{message | truncate: 200}}\nStatus: {{status}}\n\n📋 Kliknij aby zobaczyć szczegóły"
    fields:
      - {label: "ID", name: "id", widget: "number"}
      - {label: "Imię i nazwisko", name: "name", widget: "string"}
      - {label: "E-mail", name: "email", widget: "string"}
      - {label: "Telefon", name: "phone", widget: "string"}
      - {label: "Temat", name: "subject", widget: "string"}
      - {label: "Wiadomość", name: "message", widget: "text"}
      - {label: "Zgoda RODO", name: "consent", widget: "boolean"}
      - {label: "Zgoda marketing", name: "marketing", widget: "boolean"}
      - {label: "Data wysłania", name: "timestamp", widget: "datetime"}
      - {label: "Status", name: "status", widget: "select", options: ["new", "read", "replied", "archived"]}
      - {label: "Notatki", name: "notes", widget: "text", required: false}
