backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "units"
    label: "Lokale"
    folder: "data/units"
    create: true
    slug: "{{id}}-{{nr_budynku}}-{{nr_lokalu}}"
    format: "json"
    fields:
      - {label: "ID", name: "id", widget: "number"}
      - {label: "Numer budynku", name: "nr_budynku", widget: "string"}
      - {label: "Numer lokalu", name: "nr_lokalu", widget: "string"}
      - {label: "Piętro", name: "pietro", widget: "number"}
      - {label: "Powierzchnia (m²)", name: "powierzchnia", widget: "number"}
      - {label: "Dodatki", name: "dodatki", widget: "text", required: false}
      - {label: "Cena (zł)", name: "cena", widget: "number"}
      - {label: "Cena za m² (zł)", name: "cena_m2", widget: "number"}
      - {label: "Status", name: "status", widget: "select", options: ["wolny", "sprzedany", "zarezerwowany"]}
      - {label: "URL planu", name: "plan_url", widget: "string", required: false}
      - {label: "Opis", name: "opis", widget: "text", required: false}
