backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "units"
    label: "Lokale"
    folder: "data/units"
    create: true
    slug: "{{id}}-{{nr_budynku}}-{{nr_lokalu}}"
    format: "json"
    fields:
      - {label: "ID", name: "id", widget: "number"}
      - {label: "Numer budynku", name: "nr_budynku", widget: "string"}
      - {label: "Numer lokalu", name: "nr_lokalu", widget: "string"}
      - {label: "Piętro", name: "pietro", widget: "number"}
      - {label: "Powierzchnia (m²)", name: "powierzchnia", widget: "number"}
      - {label: "Dodatki", name: "dodatki", widget: "text", required: false}
      - {label: "Cena (zł)", name: "cena", widget: "number"}
      - {label: "Cena za m² (zł)", name: "cena_m2", widget: "number"}
      - {label: "Status", name: "status", widget: "select", options: ["wolny", "sprzedany", "zarezerwowany"]}
      - {label: "URL planu", name: "plan_url", widget: "string", required: false}
      - {label: "Opis", name: "opis", widget: "text", required: false}

  - name: "contact_messages"
    label: "Wiadomości kontaktowe"
    folder: "data/contact_messages"
    create: false
    slug: "{{timestamp}}-{{name}}"
    format: "json"
    fields:
      - {label: "ID", name: "id", widget: "number"}
      - {label: "Imię i nazwisko", name: "name", widget: "string"}
      - {label: "E-mail", name: "email", widget: "string"}
      - {label: "Telefon", name: "phone", widget: "string"}
      - {label: "Temat", name: "subject", widget: "string"}
      - {label: "Wiadomość", name: "message", widget: "text"}
      - {label: "Zgoda RODO", name: "consent", widget: "boolean"}
      - {label: "Zgoda marketing", name: "marketing", widget: "boolean"}
      - {label: "Data", name: "timestamp", widget: "datetime"}
      - {label: "Status", name: "status", widget: "select", options: ["new", "read", "replied", "archived"]}
      - {label: "Notatki", name: "notes", widget: "text", required: false}
