backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "units"
    label: "Lokale"
    folder: "data/units"
    create: true
    slug: "{{id}}-{{nr_budynku}}-{{nr_lokalu}}"
    format: "json"
    sortable_fields: ["id", "nr_budynku", "nr_lokalu", "cena", "status"]
    default_sort: "id"
    default_sort_direction: "asc"
    list:
      fields:
        - {label: "Lokal", name: "nr_lokalu", widget: "string"}
        - {label: "Budynek", name: "nr_budynku", widget: "string"}
        - {label: "Piętro", name: "pietro", widget: "number"}
        - {label: "Powierzchnia (m²)", name: "powierzchnia", widget: "number"}
        - {label: "Cena (zł)", name: "cena", widget: "number"}
        - {label: "Cena za m²", name: "cena_m2_display", widget: "string"}
        - {label: "Status", name: "status", widget: "select", options: ["wolny", "sprzedany", "zarezerwowany"]}
    summary: "Lokal {{nr_lokalu}}\nBudynek {{nr_budynku}}\n{{powierzchnia}}m²\n{{cena}}zł\n{{cena_m2_display}}\nStatus: {{status}}"
    fields:
      - {label: "ID", name: "id", widget: "number"}
      - {label: "Numer budynku", name: "nr_budynku", widget: "string"}
      - {label: "Numer lokalu", name: "nr_lokalu", widget: "string"}
      - {label: "Piętro", name: "pietro", widget: "number"}
      - {label: "Powierzchnia (m²)", name: "powierzchnia", widget: "number"}
      - {label: "Dodatki", name: "dodatki", widget: "text", required: false}
      - {label: "Cena (zł)", name: "cena", widget: "number"}
      - {label: "Cena za m² (zł) - obliczana automatycznie", name: "cena_m2", widget: "hidden"}
      - {label: "Cena za m² (zł)", name: "cena_m2_display", widget: "string", required: false, hint: "Obliczana automatycznie na podstawie ceny i powierzchni"}
      - {label: "Status", name: "status", widget: "select", options: ["wolny", "sprzedany", "zarezerwowany"]}
      - {label: "URL planu", name: "plan_url", widget: "string", required: false}
      - {label: "Opis", name: "opis", widget: "text", required: false}

  - name: "contact_messages"
    label: "Wiadomości kontaktowe"
    folder: "data/contact_messages"
    create: false
    slug: "{{timestamp}}-{{name}}"
    format: "json"
    sortable_fields: ["timestamp", "name", "status"]
    default_sort: "timestamp"
    default_sort_direction: "desc"
    list:
      fields:
        - {label: "Data", name: "timestamp", widget: "datetime"}
        - {label: "Imię i nazwisko", name: "name", widget: "string"}
        - {label: "E-mail", name: "email", widget: "string"}
        - {label: "Temat", name: "subject", widget: "string"}
        - {label: "Status", name: "status", widget: "select", options: ["new", "read", "replied", "archived"]}
    fields:
      - {label: "ID", name: "id", widget: "number"}
      - {label: "Imię i nazwisko", name: "name", widget: "string"}
      - {label: "E-mail", name: "email", widget: "string"}
      - {label: "Telefon", name: "phone", widget: "string"}
      - {label: "Temat", name: "subject", widget: "string"}
      - {label: "Wiadomość", name: "message", widget: "text"}
      - {label: "Zgoda RODO", name: "consent", widget: "boolean"}
      - {label: "Zgoda marketing", name: "marketing", widget: "boolean"}
      - {label: "Data wysłania", name: "timestamp", widget: "datetime"}
      - {label: "Status", name: "status", widget: "select", options: ["new", "read", "replied", "archived"]}
      - {label: "Notatki", name: "notes", widget: "text", required: false}
